from db.config import Base
from sqlalchemy import Column, Integer, Boolean

class CalendarDoM(Base):
    __tablename__ = "calendar_dom"
    id = Column(Integer, primary_key=True, index=True)
    day_1 = Column(Boolean, unique=False, index=False)
    day_2 = Column(Boolean, unique=False, index=False)
    day_3 = Column(Boolean, unique=False, index=False)
    day_4 = Column(Boolean, unique=False, index=False)
    day_5 = Column(Boolean, unique=False, index=False)
    day_6 = Column(Boolean, unique=False, index=False)
    day_7 = Column(Boolean, unique=False, index=False)
    day_8 = Column(Boolean, unique=False, index=False)
    day_9 = Column(Boolean, unique=False, index=False)
    day_10 = Column(Boolean, unique=False, index=False)
    day_11 = Column(Boolean, unique=False, index=False)
    day_12 = Column(Boolean, unique=False, index=False)
    day_13 = Column(Boolean, unique=False, index=False)
    day_14 = Column(Boolean, unique=False, index=False)
    day_15 = Column(Boolean, unique=False, index=False)
    day_16 = Column(Boolean, unique=False, index=False)
    day_17 = Column(Boolean, unique=False, index=False)
    day_18 = Column(Boolean, unique=False, index=False)
    day_19 = Column(Boolean, unique=False, index=False)
    day_20 = Column(Boolean, unique=False, index=False)
    day_21 = Column(Boolean, unique=False, index=False)
    day_22 = Column(Boolean, unique=False, index=False)
    day_23 = Column(Boolean, unique=False, index=False)
    day_24 = Column(Boolean, unique=False, index=False)
    day_25 = Column(Boolean, unique=False, index=False)
    day_26 = Column(Boolean, unique=False, index=False)
    day_27 = Column(Boolean, unique=False, index=False)
    day_28 = Column(Boolean, unique=False, index=False)
    day_29 = Column(Boolean, unique=False, index=False)
    day_30 = Column(Boolean, unique=False, index=False)
    day_31 = Column(Boolean, unique=False, index=False)
