spring:
  application:
    name: binance-data-collection
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    history-table: schema_version
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: kafka:9092
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.oyakov.binance_data_collection.kafka.deserializer.CommandMarkerDeserializer
      auto-offset-reset: earliest

binance:
  rest:
    base-url: https://api.binance.com
  websocket:
    base-url: wss://stream.binance.com:9443/ws/%s@kline_%s
  data:
    config-topic: config-ss
    kline:
      kafka-topic: binance-kline
      kafka-consumer-group: binance-data-collection
      intervals: 5m,15m,1h,1d,1w,1M
      symbols: btcusdt,ethusdt

