version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - BOT_TOKEN=6853220461:AAGIJo2a3GIMMqgz1w9iISW3Lv7ZnvAoRa8
      - COROUTINE_DEBUG=True
      - OPENAI_URL=http://localhost:8080/v1
      - OPENAI_TOKEN=lm-studio
      - LLM_MODEL=lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
    ports:
      - "8443:8443"  # Change the port as needed

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  local-ai:
    image: localai/localai:latest-aio-cpu
    container_name: local-ai
    ports:
      - "8080:8080"

volumes:
  pgdata:
