version: '3.8'

services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
      local-ai:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - LOCAL_AI_URL=http://local-ai:8080
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  local-ai:
    image: localai/localai:latest-aio-cpu
    container_name: local-ai
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/models || exit 1"]
      interval: 10s
      timeout: 500s
      retries: 50

volumes:
  pgdata:
