version: '3.8'

services:
  # Health Metrics Exporter as a Docker service
  health-metrics-exporter:
    image: nginx:alpine
    container_name: health-metrics-exporter
    ports:
      - "8091:80"
    volumes:
      - ./scripts/health-exporter-nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/health-metrics.sh:/usr/local/bin/health-metrics.sh
    networks:
      - testnet-network
    command: >
      sh -c "
        apk add --no-cache curl jq &&
        chmod +x /usr/local/bin/health-metrics.sh &&
        nginx -g 'daemon off;'
      "
    restart: unless-stopped
    depends_on:
      - postgres-testnet
      - kafka-testnet
      - elasticsearch-testnet
      - binance-trader-macd-testnet
      - binance-data-collection-testnet

networks:
  testnet-network:
    external: true
