{
 "title": "BTCUSDT",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Book",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Bids By Quantity",
     "type": "table",
     "gridPos": { "h": 14, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT price, quantity FROM order_books WHERE (symbol = 'BTCUSDT' AND type = 'bid') LIMIT 50 "
      }
     ]
    },
    {
     "title": "Top Asks By Quantity",
     "type": "table",
     "gridPos": { "h": 14, "w": 4, "x": 5, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT price, quantity FROM order_books WHERE (symbol = 'BTCUSDT' AND type = 'ask') LIMIT 50 "
      }
     ]
    },
    {
     "title": "Account - Pair Balance",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT\n  balance ->> 'asset' AS asset,\n  TO_CHAR((balance ->> 'free')::numeric, 'FM999999990.00000000') AS free,\n  TO_CHAR((balance ->> 'locked')::numeric, 'FM999999990.00000000') AS locked\nFROM\n  accounts,\n  LATERAL jsonb_array_elements(balances::jsonb) AS balance\nWHERE\n  (balance ->> 'asset') IN ('BTC', 'USDT')\nLIMIT 50;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Asset Price",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT last_price FROM tickers WHERE symbol = 'BTCUSDT' ORDER BY display_close_time DESC LIMIT 1 "
      }
     ]
    },
    {
     "title": "Price Change %",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT price_change_percent FROM tickers WHERE symbol = 'BTCUSDT' ORDER BY display_close_time LIMIT 1 "
      }
     ]
    }
   ]
  },
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Our Last Orders",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  o.display_transact_time as time, \n  o.side, \n  o.type,\n  o.orig_qty, \n  o.executed_qty, \n  o.cummulative_quote_qty as quote_qty, \n  o.status, \n  o.time_in_force,\n  f.value ->> 'price' AS fill_price,\n  f.value ->> 'qty' AS fill_qty,\n  f.value ->> 'commission' AS fill_commission,\n  f.value ->> 'commissionAsset' AS fill_commission_asset,\n  f.value ->> 'tradeId' AS fill_trade_id\nFROM \n  orders o,\n  LATERAL jsonb_array_elements(o.fills::jsonb) AS f\nORDER BY \n  o.display_transact_time DESC \nLIMIT 12;\n"
    }
   ]
  },
  { "title": "Candles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Candles - Short - 6h/1m",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (timestamp) timestamp, open, close, high, low, volume, display_time AS \"time\" FROM klines WHERE symbol = 'BTCUSDT' and interval = '1m' ORDER BY timestamp desc LIMIT 360\n"
    }
   ]
  },
  {
   "title": "Candles - Long - 4d/15m",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (timestamp) timestamp, open, close, high, low, volume, display_time AS \"time\" FROM klines WHERE symbol = 'BTCUSDT' and interval = '15m' ORDER BY timestamp desc LIMIT 360\n"
    }
   ]
  },
  {
   "title": "MACD Histogram - Short",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT histogram, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  {
   "title": "MACD Histogram - Long",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT histogram, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '15m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  {
   "title": "MACD Trend 1m",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT trend, display_time, symbol, \"interval\" FROM macd_trend WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') LIMIT 50 "
    }
   ]
  },
  {
   "title": "MACD Trend 15m",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT trend, display_time, symbol, \"interval\" FROM macd_trend WHERE (symbol = 'BTCUSDT' AND \"interval\" = '15m') LIMIT 50 "
    }
   ]
  },
  {
   "title": "EMA - Short",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT ema_fast, ema_slow, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY \"timestamp\" DESC LIMIT 200 "
    }
   ]
  },
  {
   "title": "EMA - Long",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT ema_fast, ema_slow, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '15m') ORDER BY \"timestamp\" DESC LIMIT 200 "
    }
   ]
  },
  {
   "title": "MACD - Short",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT signal, macd, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  {
   "title": "MACD - Long",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT signal, macd, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '15m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  { "title": "Ticker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Ticker (24h Avg.) Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT weighted_avg_price, display_close_time, high_price, low_price, prev_close_price, ask_price FROM tickers WHERE symbol = 'BTCUSDT' ORDER BY display_close_time DESC LIMIT 360 "
    }
   ]
  },
  {
   "title": "Ticker (24h Avg.) Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT volume, display_close_time FROM tickers WHERE symbol = 'BTCUSDT' ORDER BY display_close_time DESC LIMIT 360 "
    }
   ]
  },
  { "title": "Misc. Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } }
 ]
}