global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Data Collection Service
  - job_name: 'binance-data-collection'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['binance-data-collection:8080']
    scrape_interval: 5s

  # Data Storage Service
  - job_name: 'binance-data-storage'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['binance-data-storage:8080']
    scrape_interval: 5s

  # MACD Trader Service
  - job_name: 'binance-trader-macd'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['binance-trader-macd:8080']
    scrape_interval: 5s

  # Python Frontend Service
  - job_name: 'telegram-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['telegram-frontend:8000']
    scrape_interval: 5s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  # Elasticsearch
  - job_name: 'elasticsearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 10s
