global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: binance-macd-trader-testnet
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - macd-trader-testnet:8080  # Update with the hostname/IP of the testnet trader actuator endpoint
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testnet
