global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: binance-macd-trader-testnet
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - binance-trader-macd-testnet:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testnet

  - job_name: binance-data-collection-testnet
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - binance-data-collection-testnet:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testnet

  - job_name: binance-data-storage-testnet
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - binance-data-storage-testnet:8081
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testnet

  # Health Metrics Server (All Components)
  - job_name: health-metrics-server
    static_configs:
      - targets:
          - health-metrics-server-testnet:8092
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testnet

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
