apiVersion: 1

datasources:
  - name: Prometheus Testnet
    type: prometheus
    access: proxy
    url: http://prometheus-testnet:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m