services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    networks:
      - bot_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
        - esdata:/usr/share/elasticsearch/data
        - ./install/elastic/mappings:/usr/share/elasticsearch/mappings
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://elasticsearch:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch-init:
    image: appropriate/curl
    depends_on:
      - elasticsearch
    volumes:
      - ./install/elastic/mappings:/usr/share/elasticsearch/mappings
      - ./install/elastic/init_indices.sh:/init_indices.sh
    entrypoint: ["/bin/sh", "/init_indices.sh"]
    networks:
      - bot_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - bot_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=0l0l0sha
    logging:
      driver: "none"

volumes:
  pgdata:
  esdata:
  grafana-data:

networks:
  bot_network:
    external: false
