{
 "title": "BTCUSDT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price Change %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT price_change_percent FROM tickers LIMIT 50 "
    }
   ]
  },
  { "title": "Candles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Candles - Short - 6h/1m",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (timestamp) timestamp, open, close, high, low, volume, display_time AS \"time\" FROM klines WHERE symbol = 'BTCUSDT' and interval = '1m' ORDER BY timestamp desc LIMIT 360\n"
    }
   ]
  },
  {
   "title": "MACD Histogram - Short",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT histogram, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  {
   "title": "Candles - Long - 4d/15m",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (timestamp) timestamp, open, close, high, low, volume, display_time AS \"time\" FROM klines WHERE symbol = 'BTCUSDT' and interval = '15m' ORDER BY timestamp desc LIMIT 360\n"
    }
   ]
  },
  {
   "title": "MACD Histogram - Long",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT histogram, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '15m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  },
  { "title": "Ticker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ticker (24h Avg.) Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT weighted_avg_price, display_close_time, high_price, low_price, prev_close_price, ask_price FROM tickers WHERE symbol = 'BTCUSDT' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Ticker (24h Avg.) Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT volume, display_close_time FROM tickers WHERE symbol = 'BTCUSDT' LIMIT 50 "
    }
   ]
  },
  { "title": "Misc. Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "EMA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT ema_fast, ema_slow, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY \"timestamp\" DESC LIMIT 200 "
    }
   ]
  },
  {
   "title": "MACD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT signal, macd, display_time FROM macd WHERE (symbol = 'BTCUSDT' AND \"interval\" = '1m') ORDER BY collection_time LIMIT 181 "
    }
   ]
  }
 ]
}