{
 "title": "Kline Events Expanded",
 "tags": [
  "kline",
  "metrics",
  "binance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "label_values(binance_data_collection_kline_events_received_total, symbol)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "label_values(binance_data_collection_kline_events_received_total, interval)"
   }
  ]
 },
 "panels": [
  {
   "title": "Postgres Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "binance_data_storage_postgres_connection_status"
    }
   ]
  },
  {
   "title": "Elasticsearch Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "binance_data_storage_elasticsearch_connection_status"
    }
   ]
  },
  {
   "title": "Pipeline Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_kline_events_received_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} received"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_kline_events_sent_kafka_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} sent"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_storage_kline_events_saved_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} saved"
    }
   ]
  },
  {
   "title": "Failure Signals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_kline_events_failed_kafka_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} kafka fails"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_storage_kline_events_failed_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} storage fails"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_rest_api_calls_failed_total{symbol=~\"$symbol\",interval=~\"$interval\",operation=\"warmup\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} warmup rest fails"
    }
   ]
  },
  {
   "title": "Latency Averages (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(binance_data_collection_kafka_send_duration_seconds_sum{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval])) / sum(rate(binance_data_collection_kafka_send_duration_seconds_count{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} kafka send avg"
    },
    {
     "expr": "sum(rate(binance_data_storage_postgres_save_duration_seconds_sum{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval])) / sum(rate(binance_data_storage_postgres_save_duration_seconds_count{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} postgres save avg"
    },
    {
     "expr": "sum(rate(binance_data_storage_elasticsearch_save_duration_seconds_sum{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval])) / sum(rate(binance_data_storage_elasticsearch_save_duration_seconds_count{symbol=~\"$symbol\",interval=~\"$interval\",status=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} elastic save avg"
    }
   ]
  },
  {
   "title": "Ingress Control",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_rest_api_calls_total{symbol=~\"$symbol\",interval=~\"$interval\",operation=\"warmup\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} warmup rest"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_websocket_connections_established_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} ws established"
    },
    {
     "expr": "sum by (symbol, interval) (increase(binance_data_collection_websocket_connections_failed_total{symbol=~\"$symbol\",interval=~\"$interval\"}[$__rate_interval]))",
     "legendFormat": "{{symbol}} {{interval}} ws failed"
    }
   ]
  }
 ]
}