name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build shared model
        working-directory: binance-shared-model
        run: ../mvnw -B -ntp clean install

      - name: Run service test suites
        run: ./mvnw -B -ntp -T 1C -am -pl binance-data-collection,binance-data-storage,binance-trader-grid,binance-trader-macd -DskipTests=false clean test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Telegram frontend dependencies
        working-directory: telegram-frontend-python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -e .

      - name: Run Telegram frontend tests
        working-directory: telegram-frontend-python
        run: python -m unittest discover -s tests -p '*_test.py'
